// All 32 counties of Ireland. The rare case where the natural set is already
// small AND complete — no selection needed, and no item is redundant because
// every county differs on geography, province and jurisdiction.
export default {
  id: 'counties',
  name: 'counties of Ireland',
  desc: 'All 32 counties of Ireland.',
  credit: 'all 32 — the set is complete by definition',
  examples: [
    'has a coastline',
    'you would go there on holiday',
    'is somewhere you could live without a car',
    'has a proper city',
    'gets more rain than it deserves',
    'people outside Ireland have heard of it',
  ],
  pairWith: 'has a coastline',
  items: [
    { id: 'antrim',    name: 'Antrim',    sub: 'Ulster · Northern Ireland',  tags: ['ulster','coastal','north','city'] },
    { id: 'armagh',    name: 'Armagh',    sub: 'Ulster · Northern Ireland',  tags: ['ulster','inland','north'] },
    { id: 'carlow',    name: 'Carlow',    sub: 'Leinster',                   tags: ['leinster','inland','small'] },
    { id: 'cavan',     name: 'Cavan',     sub: 'Ulster · Republic',          tags: ['ulster','inland','lakes'] },
    { id: 'clare',     name: 'Clare',     sub: 'Munster',                    tags: ['munster','coastal','west','scenic'] },
    { id: 'cork',      name: 'Cork',      sub: 'Munster · largest county',   tags: ['munster','coastal','south','city','large'] },
    { id: 'derry',     name: 'Derry',     sub: 'Ulster · Northern Ireland',  tags: ['ulster','coastal','north','city'] },
    { id: 'donegal',   name: 'Donegal',   sub: 'Ulster · Republic',          tags: ['ulster','coastal','north','scenic','remote'] },
    { id: 'down',      name: 'Down',      sub: 'Ulster · Northern Ireland',  tags: ['ulster','coastal','north'] },
    { id: 'dublin',    name: 'Dublin',    sub: 'Leinster · capital',         tags: ['leinster','coastal','east','city','urban'] },
    { id: 'fermanagh', name: 'Fermanagh', sub: 'Ulster · Northern Ireland',  tags: ['ulster','inland','lakes','remote'] },
    { id: 'galway',    name: 'Galway',    sub: 'Connacht',                   tags: ['connacht','coastal','west','city','scenic'] },
    { id: 'kerry',     name: 'Kerry',     sub: 'Munster',                    tags: ['munster','coastal','south','scenic','tourist'] },
    { id: 'kildare',   name: 'Kildare',   sub: 'Leinster',                   tags: ['leinster','inland','east','commuter'] },
    { id: 'kilkenny',  name: 'Kilkenny',  sub: 'Leinster',                   tags: ['leinster','inland','medieval'] },
    { id: 'laois',     name: 'Laois',     sub: 'Leinster · landlocked',      tags: ['leinster','inland','midlands'] },
    { id: 'leitrim',   name: 'Leitrim',   sub: 'Connacht · least populated', tags: ['connacht','inland','remote','small'] },
    { id: 'limerick',  name: 'Limerick',  sub: 'Munster',                    tags: ['munster','coastal','south','city'] },
    { id: 'longford',  name: 'Longford',  sub: 'Leinster · landlocked',      tags: ['leinster','inland','midlands','small'] },
    { id: 'louth',     name: 'Louth',     sub: 'Leinster · smallest county', tags: ['leinster','coastal','east','small'] },
    { id: 'mayo',      name: 'Mayo',      sub: 'Connacht',                   tags: ['connacht','coastal','west','scenic','remote'] },
    { id: 'meath',     name: 'Meath',     sub: 'Leinster',                   tags: ['leinster','coastal','east','commuter','ancient'] },
    { id: 'monaghan',  name: 'Monaghan',  sub: 'Ulster · Republic',          tags: ['ulster','inland','border'] },
    { id: 'offaly',    name: 'Offaly',    sub: 'Leinster · landlocked',      tags: ['leinster','inland','midlands','bog'] },
    { id: 'roscommon', name: 'Roscommon', sub: 'Connacht · landlocked',      tags: ['connacht','inland','midlands'] },
    { id: 'sligo',     name: 'Sligo',     sub: 'Connacht',                   tags: ['connacht','coastal','west','scenic'] },
    { id: 'tipperary', name: 'Tipperary', sub: 'Munster · landlocked',       tags: ['munster','inland','farming','large'] },
    { id: 'tyrone',    name: 'Tyrone',    sub: 'Ulster · Northern Ireland',  tags: ['ulster','inland','north','large'] },
    { id: 'waterford', name: 'Waterford', sub: 'Munster · oldest city',      tags: ['munster','coastal','south','city'] },
    { id: 'westmeath', name: 'Westmeath', sub: 'Leinster · landlocked',      tags: ['leinster','inland','midlands','lakes'] },
    { id: 'wexford',   name: 'Wexford',   sub: 'Leinster',                   tags: ['leinster','coastal','south','east','sunny'] },
    { id: 'wicklow',   name: 'Wicklow',   sub: 'Leinster · the garden',      tags: ['leinster','coastal','east','scenic','mountains'] },
  ],
};
