// The original corpus, normalised to the shared item shape.
//
// `tags` exist ONLY so the offline stub can fake a plausible answer — the real
// model never sees them, it just reads the name.
export default {
  id: 'emoji',
  name: 'emoji',
  desc: '90 everyday things, hand-tagged for the offline stub.',
  credit: '',
  examples: ['could be eaten', 'a magnet would attract it', 'is found in nature',
             'would hurt to step on', 'fits in a pocket', 'is alive'],
  pairWith: 'is found in nature',
  items: [

    { id: 'key', name: 'key', glyph: '🔑', tags: ['metal','tool','small','hard','manmade'] },
    { id: 'compass', name: 'compass', glyph: '🧭', tags: ['metal','tool','round','hard','manmade'] },
    { id: 'scissors', name: 'scissors', glyph: '✂️', tags: ['metal','tool','sharp','hard','dangerous','manmade'] },
    { id: 'hammer', name: 'hammer', glyph: '🔨', tags: ['metal','tool','heavy','hard','manmade'] },
    { id: 'screwdriver', name: 'screwdriver', glyph: '🪛', tags: ['metal','tool','sharp','hard','manmade'] },
    { id: 'padlock', name: 'padlock', glyph: '🔒', tags: ['metal','heavy','hard','manmade'] },
    { id: 'paperclip', name: 'paperclip', glyph: '📎', tags: ['metal','small','light','manmade'] },
    { id: 'paperclips', name: 'paperclips', glyph: '🖇️', tags: ['metal','small','light','manmade'] },
    { id: 'bolt', name: 'bolt', glyph: '🔩', tags: ['metal','small','hard','manmade'] },
    { id: 'gear', name: 'gear', glyph: '⚙️', tags: ['metal','round','hard','manmade'] },
    { id: 'old key', name: 'old key', glyph: '🗝️', tags: ['metal','small','hard','manmade'] },
    { id: 'saw', name: 'saw', glyph: '🪚', tags: ['metal','tool','sharp','dangerous','manmade'] },
    { id: 'torch', name: 'torch', glyph: '🔦', tags: ['metal','tool','electronic','manmade'] },
    { id: 'tin can', name: 'tin can', glyph: '🥫', tags: ['metal','food','round','manmade'] },
    { id: 'apple', name: 'apple', glyph: '🍎', tags: ['food','fruit','round','natural','sweet','edible'] },
    { id: 'banana', name: 'banana', glyph: '🍌', tags: ['food','fruit','soft','natural','sweet','edible'] },
    { id: 'strawberry', name: 'strawberry', glyph: '🍓', tags: ['food','fruit','small','soft','natural','sweet','edible'] },
    { id: 'lemon', name: 'lemon', glyph: '🍋', tags: ['food','fruit','round','natural','edible'] },
    { id: 'avocado', name: 'avocado', glyph: '🥑', tags: ['food','fruit','soft','natural','edible'] },
    { id: 'tomato', name: 'tomato', glyph: '🍅', tags: ['food','fruit','round','soft','natural','edible'] },
    { id: 'carrot', name: 'carrot', glyph: '🥕', tags: ['food','vegetable','hard','natural','edible'] },
    { id: 'broccoli', name: 'broccoli', glyph: '🥦', tags: ['food','vegetable','natural','edible'] },
    { id: 'corn', name: 'corn', glyph: '🌽', tags: ['food','vegetable','natural','edible'] },
    { id: 'mushroom', name: 'mushroom', glyph: '🍄', tags: ['food','plant','soft','natural','edible'] },
    { id: 'chilli', name: 'chilli', glyph: '🌶️', tags: ['food','vegetable','hot','natural','edible'] },
    { id: 'cheese', name: 'cheese', glyph: '🧀', tags: ['food','soft','edible'] },
    { id: 'pizza', name: 'pizza', glyph: '🍕', tags: ['food','hot','edible'] },
    { id: 'bread', name: 'bread', glyph: '🍞', tags: ['food','soft','edible'] },
    { id: 'chocolate', name: 'chocolate', glyph: '🍫', tags: ['food','sweet','edible'] },
    { id: 'doughnut', name: 'doughnut', glyph: '🍩', tags: ['food','round','sweet','edible'] },
    { id: 'biscuit', name: 'biscuit', glyph: '🍪', tags: ['food','round','sweet','edible'] },
    { id: 'egg', name: 'egg', glyph: '🥚', tags: ['food','round','fragile','natural','edible'] },
    { id: 'coffee', name: 'coffee', glyph: '☕', tags: ['food','liquid','hot','edible'] },
    { id: 'wine', name: 'wine', glyph: '🍷', tags: ['food','liquid','fragile','edible'] },
    { id: 'cat', name: 'cat', glyph: '🐈', tags: ['animal','alive','soft','natural'] },
    { id: 'dog', name: 'dog', glyph: '🐕', tags: ['animal','alive','soft','natural'] },
    { id: 'mouse', name: 'mouse', glyph: '🐁', tags: ['animal','alive','small','soft','natural'] },
    { id: 'bee', name: 'bee', glyph: '🐝', tags: ['animal','alive','small','light','dangerous','natural'] },
    { id: 'butterfly', name: 'butterfly', glyph: '🦋', tags: ['animal','alive','light','fragile','natural'] },
    { id: 'tortoise', name: 'tortoise', glyph: '🐢', tags: ['animal','alive','hard','natural'] },
    { id: 'octopus', name: 'octopus', glyph: '🐙', tags: ['animal','alive','soft','natural'] },
    { id: 'tree', name: 'tree', glyph: '🌳', tags: ['plant','alive','heavy','natural'] },
    { id: 'rose', name: 'rose', glyph: '🌹', tags: ['plant','alive','sharp','fragile','natural'] },
    { id: 'leaf', name: 'leaf', glyph: '🍁', tags: ['plant','light','fragile','natural'] },
    { id: 'cactus', name: 'cactus', glyph: '🌵', tags: ['plant','alive','sharp','dangerous','natural'] },
    { id: 'rock', name: 'rock', glyph: '🪨', tags: ['heavy','hard','natural'] },
    { id: 'wave', name: 'wave', glyph: '🌊', tags: ['liquid','cold','natural'] },
    { id: 'fire', name: 'fire', glyph: '🔥', tags: ['hot','dangerous','natural'] },
    { id: 'snowflake', name: 'snowflake', glyph: '❄️', tags: ['cold','light','fragile','natural'] },
    { id: 'moon', name: 'moon', glyph: '🌙', tags: ['heavy','natural','round'] },
    { id: 'lightning', name: 'lightning', glyph: '⚡', tags: ['dangerous','light','natural'] },
    { id: 'phone', name: 'phone', glyph: '📱', tags: ['electronic','metal','hard','fragile','manmade'] },
    { id: 'laptop', name: 'laptop', glyph: '💻', tags: ['electronic','metal','hard','heavy','fragile','manmade'] },
    { id: 'battery', name: 'battery', glyph: '🔋', tags: ['electronic','metal','heavy','manmade'] },
    { id: 'monitor', name: 'monitor', glyph: '🖥️', tags: ['electronic','metal','heavy','fragile','manmade'] },
    { id: 'headphones', name: 'headphones', glyph: '🎧', tags: ['electronic','manmade','soft'] },
    { id: 'camera', name: 'camera', glyph: '📷', tags: ['electronic','metal','hard','fragile','manmade'] },
    { id: 'watch', name: 'watch', glyph: '⌚', tags: ['electronic','metal','small','round','valuable','manmade'] },
    { id: 'abacus', name: 'abacus', glyph: '🧮', tags: ['tool','hard','manmade'] },
    { id: 't-shirt', name: 't-shirt', glyph: '👕', tags: ['clothing','soft','light','manmade'] },
    { id: 'gloves', name: 'gloves', glyph: '🧤', tags: ['clothing','soft','light','manmade'] },
    { id: 'shoe', name: 'shoe', glyph: '👞', tags: ['clothing','soft','manmade'] },
    { id: 'crown', name: 'crown', glyph: '👑', tags: ['metal','valuable','hard','manmade'] },
    { id: 'ring', name: 'ring', glyph: '💍', tags: ['metal','small','valuable','hard','manmade'] },
    { id: 'handbag', name: 'handbag', glyph: '👜', tags: ['clothing','soft','manmade'] },
    { id: 'guitar', name: 'guitar', glyph: '🎸', tags: ['music','hard','manmade'] },
    { id: 'trumpet', name: 'trumpet', glyph: '🎺', tags: ['metal','music','hard','valuable','manmade'] },
    { id: 'violin', name: 'violin', glyph: '🎻', tags: ['music','fragile','valuable','manmade'] },
    { id: 'drum', name: 'drum', glyph: '🥁', tags: ['music','round','manmade'] },
    { id: 'football', name: 'football', glyph: '⚽', tags: ['toy','round','light','manmade'] },
    { id: 'tennis ball', name: 'tennis ball', glyph: '🎾', tags: ['toy','round','light','small','manmade'] },
    { id: 'teddy', name: 'teddy', glyph: '🧸', tags: ['toy','soft','light','manmade'] },
    { id: 'dice', name: 'dice', glyph: '🎲', tags: ['toy','small','hard','manmade'] },
    { id: 'puzzle', name: 'puzzle', glyph: '🧩', tags: ['toy','small','hard','manmade'] },
    { id: 'kite', name: 'kite', glyph: '🪁', tags: ['toy','light','fragile','manmade'] },
    { id: 'balloon', name: 'balloon', glyph: '🎈', tags: ['toy','light','round','fragile','manmade'] },
    { id: 'car', name: 'car', glyph: '🚗', tags: ['vehicle','metal','heavy','hard','manmade'] },
    { id: 'bicycle', name: 'bicycle', glyph: '🚲', tags: ['vehicle','metal','hard','manmade'] },
    { id: 'aeroplane', name: 'aeroplane', glyph: '✈️', tags: ['vehicle','metal','heavy','hard','manmade'] },
    { id: 'sailboat', name: 'sailboat', glyph: '⛵', tags: ['vehicle','heavy','manmade'] },
    { id: 'books', name: 'books', glyph: '📚', tags: ['writing','heavy','manmade'] },
    { id: 'pencil', name: 'pencil', glyph: '✏️', tags: ['writing','small','light','sharp','manmade'] },
    { id: 'pen', name: 'pen', glyph: '🖊️', tags: ['writing','small','light','metal','manmade'] },
    { id: 'paper', name: 'paper', glyph: '📄', tags: ['writing','light','fragile','manmade'] },
    { id: 'candle', name: 'candle', glyph: '🕯️', tags: ['hot','soft','manmade'] },
    { id: 'mirror', name: 'mirror', glyph: '🪞', tags: ['fragile','hard','heavy','manmade'] },
    { id: 'soap', name: 'soap', glyph: '🧼', tags: ['soft','small','manmade'] },
    { id: 'ice', name: 'ice', glyph: '🧊', tags: ['cold','hard','liquid','natural'] },
    { id: 'plaster', name: 'plaster', glyph: '🩹', tags: ['small','light','soft','manmade'] },
    { id: 'lightbulb', name: 'lightbulb', glyph: '💡', tags: ['electronic','fragile','round','manmade'] }
  ],
};
