// 48 national flags, picked to span geography, history and flag design rather
// than to rank countries. Includes the cases that break predicates: landlocked
// states, microstates, recent independences, non-rectangular flags, and the
// two that carry a living creature.
//
// Images from flagcdn.com (free, CORS-open, no key).
const f = (id, name, sub, tags) => ({
  id, name, sub,
  thumb: `https://flagcdn.com/w160/${id}.png`,
  tags,
});

export default {
  id: 'flags',
  name: 'flags',
  credit: 'flagcdn.com',
  examples: [
    'this country is landlocked',
    'this flag has a living thing on it',
    'I could find this country on a map unprompted',
    'this country existed under this name in 1900',
    'this flag would be hard to draw from memory',
    'this country has a monarchy',
  ],
  pairWith: 'this country is in Europe',
  items: [
    f('ie','Ireland','Europe · tricolour',        ['europe','eu','island','small']),
    f('gb','United Kingdom','Europe · union flag',['europe','island','monarchy','complex']),
    f('fr','France','Europe · tricolour',         ['europe','eu','coastal','simple']),
    f('de','Germany','Europe · tricolour',        ['europe','eu','coastal','simple']),
    f('ch','Switzerland','Europe · square flag',  ['europe','landlocked','square','simple','wealthy']),
    f('np','Nepal','Asia · not rectangular',      ['asia','landlocked','unusual','mountains']),
    f('va','Vatican City','Europe · smallest state',['europe','landlocked','tiny','square','religious']),
    f('mc','Monaco','Europe · microstate',        ['europe','coastal','tiny','monarchy','simple']),
    f('jp','Japan','Asia · island nation',        ['asia','island','simple','monarchy','wealthy']),
    f('cn','China','Asia · most populous',        ['asia','coastal','large','simple']),
    f('in','India','Asia · tricolour with wheel', ['asia','coastal','large','complex']),
    f('kr','South Korea','Asia',                  ['asia','coastal','complex','wealthy']),
    f('kp','North Korea','Asia · closed state',   ['asia','coastal','isolated']),
    f('mn','Mongolia','Asia · landlocked',        ['asia','landlocked','remote','complex']),
    f('bt','Bhutan','Asia · has a dragon',        ['asia','landlocked','creature','complex','monarchy','mountains']),
    f('lk','Sri Lanka','Asia · has a lion',       ['asia','island','creature','complex']),
    f('us','United States','N America',           ['americas','coastal','large','complex']),
    f('ca','Canada','N America · maple leaf',     ['americas','coastal','large','simple','cold']),
    f('mx','Mexico','N America · has an eagle',   ['americas','coastal','creature','complex']),
    f('br','Brazil','S America · largest',        ['americas','coastal','large','complex']),
    f('ar','Argentina','S America · has a sun',   ['americas','coastal','large','complex']),
    f('bo','Bolivia','S America · landlocked',    ['americas','landlocked','mountains','complex']),
    f('py','Paraguay','S America · landlocked',   ['americas','landlocked','complex']),
    f('jm','Jamaica','Caribbean · island',        ['americas','island','small','simple']),
    f('eg','Egypt','Africa · ancient state',      ['africa','coastal','ancient','complex']),
    f('za','South Africa','Africa · post-1994',   ['africa','coastal','recent','complex']),
    f('ng','Nigeria','Africa · most populous',    ['africa','coastal','large','simple']),
    f('et','Ethiopia','Africa · never colonised', ['africa','landlocked','ancient','complex']),
    f('ke','Kenya','Africa · has a shield',       ['africa','coastal','complex']),
    f('ml','Mali','Africa · landlocked',          ['africa','landlocked','simple','desert']),
    f('ma','Morocco','Africa',                    ['africa','coastal','monarchy','simple']),
    f('ss','South Sudan','Africa · newest state', ['africa','landlocked','recent','complex']),
    f('au','Australia','Oceania · continent',     ['oceania','island','large','complex','monarchy']),
    f('nz','New Zealand','Oceania',               ['oceania','island','complex','monarchy']),
    f('fj','Fiji','Oceania · small island state', ['oceania','island','small','complex']),
    f('tv','Tuvalu','Oceania · tiny island state',['oceania','island','tiny','complex']),
    f('is','Iceland','Europe · island',           ['europe','island','small','cold','simple']),
    f('no','Norway','Europe · nordic cross',      ['europe','coastal','cold','monarchy','wealthy','simple']),
    f('pt','Portugal','Europe',                   ['europe','eu','coastal','complex']),
    f('es','Spain','Europe',                      ['europe','eu','coastal','complex','monarchy']),
    f('it','Italy','Europe · tricolour',          ['europe','eu','coastal','simple']),
    f('gr','Greece','Europe',                     ['europe','eu','coastal','island','ancient','simple']),
    f('pl','Poland','Europe · two bands',         ['europe','eu','coastal','simple']),
    f('at','Austria','Europe · landlocked',       ['europe','eu','landlocked','simple','mountains']),
    f('ua','Ukraine','Europe · two bands',        ['europe','coastal','simple']),
    f('tr','Türkiye','Europe/Asia · two continents',['europe','asia','coastal','simple']),
    f('il','Israel','Middle East · founded 1948', ['asia','coastal','recent','religious','simple']),
    f('sa','Saudi Arabia','Middle East · has text',['asia','coastal','monarchy','religious','desert']),
  ],
};
