// Maps words a person might type to the tags above. Stub only.
export const PREDICATE_TAGS = {
  magnet: ['metal'], magnetic: ['metal'], attract: ['metal'], iron: ['metal'], steel: ['metal'],
  eat: ['edible'], edible: ['edible'], food: ['food'], tasty: ['edible'], breakfast: ['edible'],
  vegetable: ['vegetable'], fruit: ['fruit'], sweet: ['sweet'],
  alive: ['alive'], living: ['alive'], animal: ['animal'], plant: ['plant'], nature: ['natural'],
  natural: ['natural'], grows: ['alive'], breathe: ['alive'],
  sharp: ['sharp'], cut: ['sharp'], dangerous: ['dangerous'], hurt: ['sharp','hard','hot'],
  step: ['sharp','hard'], painful: ['sharp','hard','hot'],
  heavy: ['heavy'], light: ['light'], weight: ['heavy'], carry: ['light','small'],
  fragile: ['fragile'], break: ['fragile'], drop: ['fragile'], delicate: ['fragile'],
  round: ['round'], roll: ['round'], ball: ['round'],
  soft: ['soft'], hard: ['hard'], squeeze: ['soft'], squish: ['soft'],
  hot: ['hot'], cold: ['cold'], burn: ['hot'], freeze: ['cold'],
  electric: ['electronic'], battery: ['electronic'], charge: ['electronic'], screen: ['electronic'],
  tool: ['tool'], fix: ['tool'], build: ['tool'],
  music: ['music'], play: ['music','toy'], toy: ['toy'], child: ['toy'],
  wear: ['clothing'], clothes: ['clothing'], clothing: ['clothing'],
  vehicle: ['vehicle'], drive: ['vehicle'], travel: ['vehicle'],
  write: ['writing'], read: ['writing'], paper: ['writing'],
  expensive: ['valuable'], valuable: ['valuable'], steal: ['valuable','small'],
  pocket: ['small'], small: ['small'], tiny: ['small'],
  water: ['liquid'], liquid: ['liquid'], drink: ['liquid'],
  float: ['light'], sink: ['heavy'], swim: ['liquid'],
  manmade: ['manmade'], made: ['manmade'], factory: ['manmade'],
};
